### ISSUE TITLE
Compile project will auto add apache license comments

### ISSUE THREAD

**Issue by leeaee** [actframework/act-starters#2]
When project using <act-starter> as parent, the Java source files will be added "Apache License" comments in the head the file.

![u4hd123smxe bamwn bmopq](https://user-images.githubusercontent.com/1191314/36084977-04cf8c1c-0ffd-11e8-8b33-f42f36dd8380.png)

Please make adding license comment optional or not to add as default.

**Comment by greenlaw110** [comment]
@leeaee do you still have this issue?
